<?php

namespace ContainerZEz5kIq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OD4ceSOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OD4ceSO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OD4ceSO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'actor' => ['privates', '.errored..service_locator.OD4ceSO.App\\Entity\\Actors', NULL, 'Cannot autowire service ".service_locator.OD4ceSO": it references class "App\\Entity\\Actors" but no such service exists.'],
        ], [
            'actor' => 'App\\Entity\\Actors',
        ]);
    }
}
