<?php

namespace ContainerZEz5kIq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SGcY3MTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SGcY3MT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SGcY3MT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'movie' => ['privates', '.errored..service_locator.SGcY3MT.App\\Entity\\Movies', NULL, 'Cannot autowire service ".service_locator.SGcY3MT": it references class "App\\Entity\\Movies" but no such service exists.'],
        ], [
            'movie' => 'App\\Entity\\Movies',
        ]);
    }
}
