<?php

namespace ContainerZEz5kIq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZY7s4Y7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZY7s4Y7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZY7s4Y7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'moviesGenre' => ['privates', '.errored..service_locator.ZY7s4Y7.App\\Entity\\MoviesGenres', NULL, 'Cannot autowire service ".service_locator.ZY7s4Y7": it references class "App\\Entity\\MoviesGenres" but no such service exists.'],
        ], [
            'moviesGenre' => 'App\\Entity\\MoviesGenres',
        ]);
    }
}
