<?php

namespace ContainerZEz5kIq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VebmjI3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VebmjI3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VebmjI3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'director' => ['privates', '.errored..service_locator.VebmjI3.App\\Entity\\Directors', NULL, 'Cannot autowire service ".service_locator.VebmjI3": it references class "App\\Entity\\Directors" but no such service exists.'],
        ], [
            'director' => 'App\\Entity\\Directors',
        ]);
    }
}
