<?php

namespace ContainerZEz5kIq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XXhQeVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XXhQeV_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XXhQeV_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ActorsController::delete' => ['privates', '.service_locator.OD4ceSO', 'get_ServiceLocator_OD4ceSOService', true],
            'App\\Controller\\ActorsController::edit' => ['privates', '.service_locator.OD4ceSO', 'get_ServiceLocator_OD4ceSOService', true],
            'App\\Controller\\ActorsController::show' => ['privates', '.service_locator.OD4ceSO', 'get_ServiceLocator_OD4ceSOService', true],
            'App\\Controller\\DirectorsController::delete' => ['privates', '.service_locator.VebmjI3', 'get_ServiceLocator_VebmjI3Service', true],
            'App\\Controller\\DirectorsController::edit' => ['privates', '.service_locator.VebmjI3', 'get_ServiceLocator_VebmjI3Service', true],
            'App\\Controller\\DirectorsController::show' => ['privates', '.service_locator.VebmjI3', 'get_ServiceLocator_VebmjI3Service', true],
            'App\\Controller\\DirectorsGenresController::delete' => ['privates', '.service_locator.JI88iln', 'get_ServiceLocator_JI88ilnService', true],
            'App\\Controller\\DirectorsGenresController::edit' => ['privates', '.service_locator.JI88iln', 'get_ServiceLocator_JI88ilnService', true],
            'App\\Controller\\DirectorsGenresController::show' => ['privates', '.service_locator.JI88iln', 'get_ServiceLocator_JI88ilnService', true],
            'App\\Controller\\MoviesController::delete' => ['privates', '.service_locator.SGcY3MT', 'get_ServiceLocator_SGcY3MTService', true],
            'App\\Controller\\MoviesController::edit' => ['privates', '.service_locator.SGcY3MT', 'get_ServiceLocator_SGcY3MTService', true],
            'App\\Controller\\MoviesController::show' => ['privates', '.service_locator.SGcY3MT', 'get_ServiceLocator_SGcY3MTService', true],
            'App\\Controller\\MoviesGenresController::delete' => ['privates', '.service_locator.ZY7s4Y7', 'get_ServiceLocator_ZY7s4Y7Service', true],
            'App\\Controller\\MoviesGenresController::edit' => ['privates', '.service_locator.ZY7s4Y7', 'get_ServiceLocator_ZY7s4Y7Service', true],
            'App\\Controller\\MoviesGenresController::show' => ['privates', '.service_locator.ZY7s4Y7', 'get_ServiceLocator_ZY7s4Y7Service', true],
            'App\\Controller\\RolesController::delete' => ['privates', '.service_locator.pc2X7em', 'get_ServiceLocator_Pc2X7emService', true],
            'App\\Controller\\RolesController::edit' => ['privates', '.service_locator.pc2X7em', 'get_ServiceLocator_Pc2X7emService', true],
            'App\\Controller\\RolesController::show' => ['privates', '.service_locator.pc2X7em', 'get_ServiceLocator_Pc2X7emService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ActorsController:delete' => ['privates', '.service_locator.OD4ceSO', 'get_ServiceLocator_OD4ceSOService', true],
            'App\\Controller\\ActorsController:edit' => ['privates', '.service_locator.OD4ceSO', 'get_ServiceLocator_OD4ceSOService', true],
            'App\\Controller\\ActorsController:show' => ['privates', '.service_locator.OD4ceSO', 'get_ServiceLocator_OD4ceSOService', true],
            'App\\Controller\\DirectorsController:delete' => ['privates', '.service_locator.VebmjI3', 'get_ServiceLocator_VebmjI3Service', true],
            'App\\Controller\\DirectorsController:edit' => ['privates', '.service_locator.VebmjI3', 'get_ServiceLocator_VebmjI3Service', true],
            'App\\Controller\\DirectorsController:show' => ['privates', '.service_locator.VebmjI3', 'get_ServiceLocator_VebmjI3Service', true],
            'App\\Controller\\DirectorsGenresController:delete' => ['privates', '.service_locator.JI88iln', 'get_ServiceLocator_JI88ilnService', true],
            'App\\Controller\\DirectorsGenresController:edit' => ['privates', '.service_locator.JI88iln', 'get_ServiceLocator_JI88ilnService', true],
            'App\\Controller\\DirectorsGenresController:show' => ['privates', '.service_locator.JI88iln', 'get_ServiceLocator_JI88ilnService', true],
            'App\\Controller\\MoviesController:delete' => ['privates', '.service_locator.SGcY3MT', 'get_ServiceLocator_SGcY3MTService', true],
            'App\\Controller\\MoviesController:edit' => ['privates', '.service_locator.SGcY3MT', 'get_ServiceLocator_SGcY3MTService', true],
            'App\\Controller\\MoviesController:show' => ['privates', '.service_locator.SGcY3MT', 'get_ServiceLocator_SGcY3MTService', true],
            'App\\Controller\\MoviesGenresController:delete' => ['privates', '.service_locator.ZY7s4Y7', 'get_ServiceLocator_ZY7s4Y7Service', true],
            'App\\Controller\\MoviesGenresController:edit' => ['privates', '.service_locator.ZY7s4Y7', 'get_ServiceLocator_ZY7s4Y7Service', true],
            'App\\Controller\\MoviesGenresController:show' => ['privates', '.service_locator.ZY7s4Y7', 'get_ServiceLocator_ZY7s4Y7Service', true],
            'App\\Controller\\RolesController:delete' => ['privates', '.service_locator.pc2X7em', 'get_ServiceLocator_Pc2X7emService', true],
            'App\\Controller\\RolesController:edit' => ['privates', '.service_locator.pc2X7em', 'get_ServiceLocator_Pc2X7emService', true],
            'App\\Controller\\RolesController:show' => ['privates', '.service_locator.pc2X7em', 'get_ServiceLocator_Pc2X7emService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ActorsController::delete' => '?',
            'App\\Controller\\ActorsController::edit' => '?',
            'App\\Controller\\ActorsController::show' => '?',
            'App\\Controller\\DirectorsController::delete' => '?',
            'App\\Controller\\DirectorsController::edit' => '?',
            'App\\Controller\\DirectorsController::show' => '?',
            'App\\Controller\\DirectorsGenresController::delete' => '?',
            'App\\Controller\\DirectorsGenresController::edit' => '?',
            'App\\Controller\\DirectorsGenresController::show' => '?',
            'App\\Controller\\MoviesController::delete' => '?',
            'App\\Controller\\MoviesController::edit' => '?',
            'App\\Controller\\MoviesController::show' => '?',
            'App\\Controller\\MoviesGenresController::delete' => '?',
            'App\\Controller\\MoviesGenresController::edit' => '?',
            'App\\Controller\\MoviesGenresController::show' => '?',
            'App\\Controller\\RolesController::delete' => '?',
            'App\\Controller\\RolesController::edit' => '?',
            'App\\Controller\\RolesController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ActorsController:delete' => '?',
            'App\\Controller\\ActorsController:edit' => '?',
            'App\\Controller\\ActorsController:show' => '?',
            'App\\Controller\\DirectorsController:delete' => '?',
            'App\\Controller\\DirectorsController:edit' => '?',
            'App\\Controller\\DirectorsController:show' => '?',
            'App\\Controller\\DirectorsGenresController:delete' => '?',
            'App\\Controller\\DirectorsGenresController:edit' => '?',
            'App\\Controller\\DirectorsGenresController:show' => '?',
            'App\\Controller\\MoviesController:delete' => '?',
            'App\\Controller\\MoviesController:edit' => '?',
            'App\\Controller\\MoviesController:show' => '?',
            'App\\Controller\\MoviesGenresController:delete' => '?',
            'App\\Controller\\MoviesGenresController:edit' => '?',
            'App\\Controller\\MoviesGenresController:show' => '?',
            'App\\Controller\\RolesController:delete' => '?',
            'App\\Controller\\RolesController:edit' => '?',
            'App\\Controller\\RolesController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
