<?php

namespace ContainerZEz5kIq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JI88ilnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JI88iln' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JI88iln'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'directorsGenre' => ['privates', '.errored..service_locator.JI88iln.App\\Entity\\DirectorsGenres', NULL, 'Cannot autowire service ".service_locator.JI88iln": it references class "App\\Entity\\DirectorsGenres" but no such service exists.'],
        ], [
            'directorsGenre' => 'App\\Entity\\DirectorsGenres',
        ]);
    }
}
