<?php

namespace ContainerZEz5kIq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDirectorsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VebmjI3.App\Entity\Directors' shared service.
     *
     * @return \App\Entity\Directors
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.VebmjI3": it references class "App\\Entity\\Directors" but no such service exists.');
    }
}
