<?php

namespace ContainerZEz5kIq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDirectorsGenresService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.JI88iln.App\Entity\DirectorsGenres' shared service.
     *
     * @return \App\Entity\DirectorsGenres
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.JI88iln": it references class "App\\Entity\\DirectorsGenres" but no such service exists.');
    }
}
