<?php

namespace ContainerZEz5kIq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMoviesGenresTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\MoviesGenresType' shared autowired service.
     *
     * @return \App\Form\MoviesGenresType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/MoviesGenresType.php';

        return $container->privates['App\\Form\\MoviesGenresType'] = new \App\Form\MoviesGenresType();
    }
}
