<?php

namespace ContainerZEz5kIq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMoviesGenresService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZY7s4Y7.App\Entity\MoviesGenres' shared service.
     *
     * @return \App\Entity\MoviesGenres
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ZY7s4Y7": it references class "App\\Entity\\MoviesGenres" but no such service exists.');
    }
}
