<?php

namespace ContainerZEz5kIq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMoviesTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\MoviesType' shared autowired service.
     *
     * @return \App\Form\MoviesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/MoviesType.php';

        return $container->privates['App\\Form\\MoviesType'] = new \App\Form\MoviesType();
    }
}
