<?php

namespace ContainerQaKBBsh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_11yIPTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1_1yIPT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1_1yIPT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ActorsController::delete' => ['privates', '.service_locator.OD4ceSO', 'get_ServiceLocator_OD4ceSOService', true],
            'App\\Controller\\ActorsController::edit' => ['privates', '.service_locator.OD4ceSO', 'get_ServiceLocator_OD4ceSOService', true],
            'App\\Controller\\ActorsController::show' => ['privates', '.service_locator.OD4ceSO', 'get_ServiceLocator_OD4ceSOService', true],
            'App\\Controller\\MoviesController::delete' => ['privates', '.service_locator.SGcY3MT', 'get_ServiceLocator_SGcY3MTService', true],
            'App\\Controller\\MoviesController::edit' => ['privates', '.service_locator.SGcY3MT', 'get_ServiceLocator_SGcY3MTService', true],
            'App\\Controller\\MoviesController::show' => ['privates', '.service_locator.SGcY3MT', 'get_ServiceLocator_SGcY3MTService', true],
            'App\\Controller\\RolesController::delete' => ['privates', '.service_locator.pc2X7em', 'get_ServiceLocator_Pc2X7emService', true],
            'App\\Controller\\RolesController::edit' => ['privates', '.service_locator.pc2X7em', 'get_ServiceLocator_Pc2X7emService', true],
            'App\\Controller\\RolesController::show' => ['privates', '.service_locator.pc2X7em', 'get_ServiceLocator_Pc2X7emService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ActorsController:delete' => ['privates', '.service_locator.OD4ceSO', 'get_ServiceLocator_OD4ceSOService', true],
            'App\\Controller\\ActorsController:edit' => ['privates', '.service_locator.OD4ceSO', 'get_ServiceLocator_OD4ceSOService', true],
            'App\\Controller\\ActorsController:show' => ['privates', '.service_locator.OD4ceSO', 'get_ServiceLocator_OD4ceSOService', true],
            'App\\Controller\\MoviesController:delete' => ['privates', '.service_locator.SGcY3MT', 'get_ServiceLocator_SGcY3MTService', true],
            'App\\Controller\\MoviesController:edit' => ['privates', '.service_locator.SGcY3MT', 'get_ServiceLocator_SGcY3MTService', true],
            'App\\Controller\\MoviesController:show' => ['privates', '.service_locator.SGcY3MT', 'get_ServiceLocator_SGcY3MTService', true],
            'App\\Controller\\RolesController:delete' => ['privates', '.service_locator.pc2X7em', 'get_ServiceLocator_Pc2X7emService', true],
            'App\\Controller\\RolesController:edit' => ['privates', '.service_locator.pc2X7em', 'get_ServiceLocator_Pc2X7emService', true],
            'App\\Controller\\RolesController:show' => ['privates', '.service_locator.pc2X7em', 'get_ServiceLocator_Pc2X7emService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ActorsController::delete' => '?',
            'App\\Controller\\ActorsController::edit' => '?',
            'App\\Controller\\ActorsController::show' => '?',
            'App\\Controller\\MoviesController::delete' => '?',
            'App\\Controller\\MoviesController::edit' => '?',
            'App\\Controller\\MoviesController::show' => '?',
            'App\\Controller\\RolesController::delete' => '?',
            'App\\Controller\\RolesController::edit' => '?',
            'App\\Controller\\RolesController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ActorsController:delete' => '?',
            'App\\Controller\\ActorsController:edit' => '?',
            'App\\Controller\\ActorsController:show' => '?',
            'App\\Controller\\MoviesController:delete' => '?',
            'App\\Controller\\MoviesController:edit' => '?',
            'App\\Controller\\MoviesController:show' => '?',
            'App\\Controller\\RolesController:delete' => '?',
            'App\\Controller\\RolesController:edit' => '?',
            'App\\Controller\\RolesController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
