<?php

namespace ContainerQaKBBsh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActorsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OD4ceSO.App\Entity\Actors' shared service.
     *
     * @return \App\Entity\Actors
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.OD4ceSO": it references class "App\\Entity\\Actors" but no such service exists.');
    }
}
