<?php

namespace ContainerQaKBBsh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMoviesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SGcY3MT.App\Entity\Movies' shared service.
     *
     * @return \App\Entity\Movies
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.SGcY3MT": it references class "App\\Entity\\Movies" but no such service exists.');
    }
}
