<?php

namespace ContainerQaKBBsh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRolesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.pc2X7em.App\Entity\Roles' shared service.
     *
     * @return \App\Entity\Roles
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.pc2X7em": it references class "App\\Entity\\Roles" but no such service exists.');
    }
}
